from __future__ import annotations

from functools import cached_property
from typing import List, Optional
from dataclasses import dataclass, field


# ----------------------------------------
# Model Structure
# ----------------------------------------
# Pysch sheet data:
# Meet
#  └── Event
#       └── Entry
#            └── Swimmer
#
# Heat sheet data
# Meet
#  └── Event
#       └── Heat
#            └── Lane
#                 └── Entry
#
# Meet
#  ├── settings (MeetSettings)
#  └── events[]
#
# Event
#  ├── event_number
#  ├── name
#  ├── entries[]   ← Psych sheet data
#  └── heats[]     ← Generated during seeding
#
# Heat
#  ├── heat_number
#  └── lanes[]
#
# Lane
#  ├── lane_number
#  └── entry
#
# Entry
#  ├── swimmer
#  ├── event
#  ├── seed_num
#  ├── entry_time
#  ├── heat_number
#  └── lane_number
#
# Swimmer
#  ├── name
#  ├── age
#  ├── gender
#  └── team
#
# MeetSettings
#  ├── lanes
#  ├── circle_seed_top_n_heats
#  ├── distance_event_order
#  └── long_distance_events
# ----------------------------------------

# --------------------------------------------------
# Meet Settings
# --------------------------------------------------
@dataclass
class MeetSettings:
    lanes: int = 8
    circle_seed_top_n_heats: int = 1
    distance_event_order: str = "Fast to Slow"  # or "Slow to Fast"
    long_distance_events: set[int] = field(
        default_factory=set
    )

# --------------------------------------------------
# Swimmer
# --------------------------------------------------
@dataclass
class Swimmer:
    name: str
    gender: str
    age: int
    team: str

# --------------------------------------------------
# Entry
# --------------------------------------------------
@dataclass
class Entry:
    swimmer: Swimmer

    # Back reference
    event: Optional["Event"] = None

    # Psych sheet data
    seed_num: int = 0
    entry_time: str = 'NT'

    # Generated during seeding
    heat_number: Optional[int] = None
    lane_number: Optional[int] = None

# --------------------------------------------------
# Lane
# --------------------------------------------------
@dataclass
class Lane:
    lane_number: int
    entry: Optional[Entry] = None

# --------------------------------------------------
# Heat
# --------------------------------------------------
@dataclass
class Heat:
    heat_number: int
    lanes: list[Lane] = field(default_factory=list)

    def get_lane(self, lane_number: int) -> Optional[Lane]:
        for lane in self.lanes:
            if lane.lane_number == lane_number:
                return lane
        return None

# --------------------------------------------------
# Event
# --------------------------------------------------
@dataclass
class Event:
    event_number: int
    name: str

    # Parsed from psych sheet
    entries: list[Entry] = field(default_factory=list)

    # Generated by seeding
    heats: list[Heat] = field(default_factory=list)

    def add_entry(self, entry: Entry) -> None:
        entry.event = self
        self.entries.append(entry)

# --------------------------------------------------
# Meet
# --------------------------------------------------
@dataclass
class Meet:
    name: str
    settings: MeetSettings = field(default_factory=MeetSettings)
    events: list[Event] = field(default_factory=list)

    def get_event(self, event_number: int) -> Optional[Event]:
        for event in self.events:
            if event.event_number == event_number:
                return event
        return None

    def add_event(self, event: Event) -> None:
        self.events.append(event)

    @cached_property
    def entries(self):
        return list(self.all_entries())

    def all_entries(self):
        for event in self.events:
            for heat in event.heats:
                for lane in heat.lanes:
                    if lane.entry:
                        yield lane.entry

    def all_swimmers(self):
        return {e.swimmer for e in self.all_entries()}

